return {
	require("lentent.plugins.neoconf"),
	require("lentent.plugins.lazydev"),
	require("lentent.plugins.nvim-web-devicons"),
	require("lentent.plugins.bufferline"),
	require("lentent.plugins.lualine"),
	require("lentent.plugins.onedark"),
	require("lentent.plugins.colorizer"),
	require("lentent.plugins.treesitter"),
	require("lentent.plugins.gitsigns"),
	require("lentent.plugins.nvim-tree"),
	require("lentent.plugins.notify"),
	require("lentent.plugins.nvim-test"),
	require("lentent.plugins.textcase"),
	require("lentent.plugins.arrow"),
	require("lentent.plugins.telescope"),
	-- require("lentent.plugins.neodev"),
	require("lentent.plugins.noice"),
	-- require("lentent.plugins.lspsaga"),
	require("lentent.plugins.precognition"),
}
